baseURL: https://nickmckay.github.io/
theme: hugo-apero
languageCode: en
title: Nick McKay - Paleoclimate Scientist
author: Nick McKay
copyright: ''
googleAnalytics: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
pagination:
  enableEmoji: yes
  ignoreFiles:
    - \.Rmd$
    - \.Rmarkdown$
    - _cache$
    - \.knit\.md$
    - \.utf8\.md$
  pagerSize: 5
  preserveTaxonomyNames: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  comments: utterances
  custom_theme: ''
  customheadingFontFamily: Fraunces
  customtextFontFamily: Commissioner
  description: Professor at Northern Arizona University, studying paleoclimate dynamics using natural records of past climate variability to understand our climate future.
  favicon: /img/favicon.ico
  giscus:
    category: Comments
    category_id: '[category ID]'
    emit_metadata: '0'
    lang: en
    mapping: pathname
    reactions_enabled: '1'
    repo: apreshill/apero
    repo_id: '[REPO ID]='
    theme: light
  headingFontFamily: sans-serif
  logo: /img/blogophonic-mark-dark.png
  mainSections:
    - blog
    - project
    - talk
  math:
    renderer: katex
  navallcaps: yes
  orgLocal: Flagstaff, Arizona
  orgName: Northern Arizona University
  sharing_image: /img/papillons.jpg
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/nickmckay
    - icon: x-twitter
      icon_pack: fab
      url: https://twitter.com/npmckay
    - icon: orcid
      icon_pack: ai
      url: http://orcid.org/0000-0003-3598-5113
  socialInFooter: yes
  socialInHeader: no
  textFontFamily: sans-serif
  theme: sky
  twitter: npmckay
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: nickmckay/nickmckay.github.io
    theme: boxy-light
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  footer:
    - name: Contact
      title: Contact Dr. McKay
      url: /contact/
      weight: 1
    - name: License
      title: License
      url: /license/
      weight: 2
  header:
    - name: About
      title: About Nick McKay
      url: /about/
      weight: 1
    - name: Research
      title: Research Areas
      url: /research/
      weight: 2
    - name: Blog
      title: Research Blog
      url: /blog/
      weight: 3
    - name: Projects
      title: Project Portfolio
      url: /project/
      weight: 4
    - name: Publications
      title: Publications
      url: /publications/
      weight: 5
    - name: Opportunities
      title: Graduate Students
      url: /opportunities/
      weight: 6
    - name: Contact
      title: Get in Touch
      url: /contact/
      weight: 7
privacy:
  disqus:
    disable: yes
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: no
    simple: yes
  vimeo:
    disable: no
    enableDNT: yes
    simple: yes
  x:
    disable: no
    enableDNT: yes
    simple: no
  youtube:
    disable: no
    privacyEnhanced: yes
