name: Weekly Publications Update

on:
  schedule:
    # Run every Sunday at 6:00 AM UTC (adjust as needed)
    - cron: '0 6 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-publications:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.0'
        
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
        
    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ~/.local/share/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-
          
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
        
    - name: Install R dependencies
      run: |
        R -e "if (!require('renv')) install.packages('renv')"
        R -e "renv::restore()"
        
    - name: Update publications database
      run: |
        R -e "source('R/build.R')"
        
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add R/data/*.csv
        git commit -m "Weekly publications database update 🤖

        Updates publication data from Google Scholar
        
        Generated with GitHub Actions on $(date)"
        git push
        
    - name: Build and deploy site
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        R -e "blogdown::build_site(build_rmd = TRUE)"
        
    - name: Deploy to GitHub Pages
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
        
    - name: No changes notification
      if: steps.verify-changed-files.outputs.changed == 'false'
      run: |
        echo "No publication updates needed - database is current!"